using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using APMoodle.Models;
using APMoodle.Services.Interfaces;
using System.ComponentModel.DataAnnotations;

namespace APMoodle.Pages.BackEnd
{
    public class RegisterModel : PageModel
    {
        private readonly IStudentService _studentService;
        private readonly IEmailService _emailService;

        public RegisterModel(IStudentService studentService, IEmailService emailService)
        {
            _emailService = emailService;
            _studentService = studentService;
        }

        [BindProperty]
        public string FullName { get; set; } = string.Empty;

        [BindProperty]
        public string Dob { get; set; } = string.Empty;

        [BindProperty]
        public string Contact { get; set; } = string.Empty;

        [BindProperty]
        [EmailAddress]
        public string Email { get; set; } = string.Empty;

        [BindProperty]
        public string Gender { get; set; } = string.Empty;

        public string? Message { get; set; }
        public bool IsSuccess { get; set; }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            // Validate required fields
            if (string.IsNullOrEmpty(FullName) || string.IsNullOrEmpty(Email) || string.IsNullOrEmpty(Contact))
            {
                Message = "Please fill in all required fields.";
                IsSuccess = false;
                return Page();
            }

            // Validate email format
            if (!IsValidEmail(Email))
            {
                Message = "Please enter a valid email address.";
                IsSuccess = false;
                return Page();
            }

            // Check if email already exists
            if (await _studentService.StudentExistsAsync(Email))
            {
                Message = "Email already registered. Please use a different email or login.";
                IsSuccess = false;
                return Page();
            }

            DateOnly dobDateOnly;
            if (DateOnly.TryParse(Dob, out var dob))
            {
                dobDateOnly = dob;
            }
            else
            {
                // Default value if parsing fails
                dobDateOnly = DateOnly.FromDateTime(DateTime.Today);
            }

            // Create new student (NO password - will be generated by admin)
            var student = new Student
            {
                Name = FullName,
                Email = Email,
                PhoneNumber = Contact,
                Gender = Gender,
                Password = "", // Empty - will be set by admin when approved
                Status = "Pending",  // Waiting for admin approval
                RegisteredDate = DateTime.UtcNow,
                DOB = dobDateOnly
            };

            var success = await _studentService.CreateStudentAsync(student);

            if (success)
            {
                // Send email notification to student
                await _emailService.SendRegistrationPendingEmailAsync(Email, FullName);

                Message = "Registration successful! Please check your email for confirmation. Your account will be activated by the admin within 24-48 hours. You will receive your login credentials via email once approved.";
                IsSuccess = true;
                return Page();
            }

            Message = "Registration failed. Please try again later.";
            IsSuccess = false;
            return Page();
        }

        private bool IsValidEmail(string email)
        {
            try
            {
                var addr = new System.Net.Mail.MailAddress(email);
                return addr.Address == email;
            }
            catch
            {
                return false;
            }
        }
    }
}